const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], 
});

import "../styles/globals.css";
import { Poppins } from "next/font/google";
export const metadata = {
  title: "Bora Viajar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}